version: '3'
services:
  llm-app:
    restart: always
    image: dev-llm:v141
    build:
      context: ../
      dockerfile: llm-dev/Dockerfile
    volumes:
      - ../src:/workspace/src
    container_name: LLM 
    tty: true
    ports: 
      - '8888:8888'
    command: jupyter-lab --ip 0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token=''
    working_dir: /workspace
    shm_size: '256gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]